server:
  port: 8863

spring:
  application:
    name: product-service

eureka:
  client:
    #healthcheck:
    #enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

env: dev
branch: master
